No exception error 
I am in finally bloc
test completed
